version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always

  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      kafka-topics --bootstrap-server kafka:29092 --list
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic views --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic rating --replication-factor 1 --partitions 1
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "

  nginx:
    container_name: nginx
    image: nginx:1.23
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - fastapi
    ports:
      - "443:443"
    restart: always

  fastapi:
    build: .
    container_name: ugc_fastapi
    expose:
      - "8001"
    env_file:
      - .env
    depends_on:
      - zookeeper
      - kafka
    restart: on-failure

  etl:
    container_name: ugc_etl
    build:
      context: ./etl
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - fastapi
      - kafka
      - init-kafka
      - clickhouse-node1
      - clickhouse-node2
      - clickhouse-node3
      - clickhouse-node4
      - clickhouse-node5
      - clickhouse-node6
    restart: always

  clickhouse-zookeeper:
    image: zookeeper:3.5
    container_name: clickhouse-zookeeper
    hostname: clickhouse-zookeeper
    restart: always

  clickhouse-node1:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    restart: always
    volumes:
      - ./ch_conf/node1:/etc/clickhouse-server
      - ./ch_conf/sql/node1.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - zookeeper

  clickhouse-node2:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    restart: always
    volumes:
      - ./ch_conf/node2:/etc/clickhouse-server
      - ./ch_conf/sql/node1.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - zookeeper

  clickhouse-node3:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    restart: always
    volumes:
      - ./ch_conf/node3:/etc/clickhouse-server
      - ./ch_conf/sql/node3.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - zookeeper

  clickhouse-node4:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    restart: always
    volumes:
      - ./ch_conf/node4:/etc/clickhouse-server
      - ./ch_conf/sql/node3.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - zookeeper

  clickhouse-node5:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node5
    hostname: clickhouse-node5
    restart: always
    volumes:
      - ./ch_conf/node5:/etc/clickhouse-server
      - ./ch_conf/sql/node5.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - zookeeper

  clickhouse-node6:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node6
    hostname: clickhouse-node6
    restart: always
    volumes:
      - ./ch_conf/node6:/etc/clickhouse-server
      - ./ch_conf/sql/node5.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - zookeeper
