version: '3'
services:

  db:
    container_name: auth_db
    image: postgres:14.3
    environment:
      POSTGRES_DB: $PG_DB
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
    volumes:
      - ./auth/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - .env
    restart: always
    networks:
      - service-network

  auth:
    container_name: auth
    build:
      context: .
      args:
        PROJECT_ENV: production
    env_file:
      - .env
    entrypoint: ["sh", "src/run.sh"]
    depends_on:
      - db
      - redis
    expose:
      - 5000
    restart: always
    networks:
      - service-network

  redis:
    container_name: auth_redis
    image: redis:7.0.4-alpine
    expose:
      - 6379
    restart: always
    volumes:
      - cache:/data
    networks:
      - service-network

  nginx:
      container_name: auth_nginx
      image: nginx:1.23
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/configs:/etc/nginx/conf.d:ro
      depends_on:
        - auth
      ports:
        - "80:80"
        - "10443:443"
      restart: always
      networks:
        - service-network
      logging:
        driver: gelf
        options:
          gelf-address: udp://localhost:5047
          tag: auth_nginx

  jaeger:
    container_name: auth_jaeger
    image: jaegertracing/all-in-one:latest
    depends_on:
      - nginx
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - service-network

networks:
  service-network:
    external: true

volumes:
  db_data:
  cache: