version: '3'

services:
  clickhouse-zookeeper:
    image: zookeeper:3.5
    container_name: clickhouse-zookeeper
    hostname: clickhouse-zookeeper
    restart: always

  clickhouse-node1:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./node1:/etc/clickhouse-server
      - ./sql/node1.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - zookeeper

  clickhouse-node2:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    restart: always
    volumes:
      - ./node2:/etc/clickhouse-server
      - ./sql/node1.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - zookeeper

  clickhouse-node3:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    restart: always
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - ./node3:/etc/clickhouse-server
      - ./sql/node3.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - zookeeper

  clickhouse-node4:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    restart: always
    volumes:
      - ./node4:/etc/clickhouse-server
      - ./sql/node3.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - zookeeper
    networks:
      - service-network

  clickhouse-node5:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node5
    hostname: clickhouse-node5
    restart: always
    ports:
      - "8125:8123"
      - "9002:9000"
    volumes:
      - ./node5:/etc/clickhouse-server
      - ./sql/node5.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - zookeeper

  clickhouse-node6:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node6
    hostname: clickhouse-node6
    restart: always
    volumes:
      - ./node6:/etc/clickhouse-server
      - ./sql/node5.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - zookeeper
