name: pre-commit

on:
  push:
    branches: [main, task_10_CICD]
  pull_request:
    branches: [main]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Linting
        run: |
            pre-commit run trailing-whitespace --all-files
            pre-commit run double-quote-string-fixer --all-files
            pre-commit run black --all-files
            pre-commit run flake8 --all-files






